spring:
  profiles:
    active:
      - dog
      - EN
      - prod

guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrlForDB

---

spring:
  profiles: prod

guru:
  username: ProdYmlUserName
  password: ProdYmlPassword
  jdbcurl: ProdYmlUrlForDB


